export const SET_SAGA_CODE = 'SET_SAGA_CODE';
export const SET_REDUCER_CODE = 'SET_REDUCER_CODE';
export const SET_ACTIONS_CODE = 'SET_ACTIONS_CODE';
export const SET_ACTION_TYPES_CODE = 'SET_ACTION_TYPES_CODE';
export const SET_HOC_CODE = 'SET_HOC_CODE';
export const SET_SMART_CODE = 'SET_SMART_CODE';
export const SET_DUMB_CODE = 'SET_DUMB_CODE';
export const SET_STYLES_CODE = 'SET_STYLES_CODE';
export const SET_JSON_FORM_SCHEMA_CODE = 'SET_JSON_FORM_SCHEMA_CODE';
export const SET_JSON_FORM_UISCHEMA_CODE = 'SET_JSON_FORM_UISCHEMA_CODE';

