export const SET_SAGA_CODE = 'SET_SAGA_CODE';
export const SET_REDUCER_CODE = 'SET_REDUCER_CODE';
export const SET_ACTIONS_CODE = 'SET_ACTIONS_CODE';
export const SET_ACTION_TYPES_CODE = 'SET_ACTION_TYPES_CODE';
export const SET_HOC_CODE = 'SET_HOC_CODE';
export const SET_SMART_CODE = 'SET_SMART_CODE';

