export const GET_ALL_PROJECT_TYPES = 'GET_ALL_PROJECT_TYPES';
export const SET_ALL_PROJECT_TYPES = 'SET_ALL_PROJECT_TYPES';
export const SET_PROJECT_TYPE = 'SET_PROJECT_TYPE';
export const SET_SELECTED_PROJECT_TYPE = 'SET_SELECTED_PROJECT_TYPE';
export const DELETE_PROJECT_TYPE = 'DELETE_PROJECT_TYPE';

