export const GET_ALL_COMPONENTS = 'GET_ALL_COMPONENTS';
export const SET_ALL_COMPONENTS = 'SET_ALL_COMPONENTS';
export const SET_COMPONENT = 'SET_COMPONENT';
export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const FILTER_COMPONENTS = 'FILTER_COMPONENTS';


