export const SET_PROJECT_SETTINGS_NAME = 'SET_PROJECT_SETTINGS_NAME';
export const SET_PROJECT_SETTINGS_TYPE = 'SET_PROJECT_SETTINGS_TYPE';
export const SET_PROJECT_SETTINGS_TECHNO = 'SET_PROJECT_SETTINGS_TECHNO';
export const SET_PROJECT_SETTINGS_COMPONENT_TYPE = 'SET_PROJECT_SETTINGS_COMPONENT_TYPE';
export const SET_PROJECT_SETTINGS_HAS_JSON_FORM = 'SET_PROJECT_SETTINGS_HAS_JSON_FORM';
export const SET_PROJECT_SETTINGS_JSON_FORM = 'SET_PROJECT_SETTINGS_JSON_FORM';
export const SET_PROJECT_SETTINGS_ERROR = 'SET_PROJECT_SETTINGS_ERROR';
export const SET_PROJECT_DESTINATION = 'SET_PROJECT_DESTINATION';
