export const GET_ALL_PROVIDERS = 'GET_ALL_PROVIDERS';
export const SET_ALL_PROVIDERS = 'SET_ALL_PROVIDERS';
export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_SELECTED_PROVIDER = 'SET_SELECTED_PROVIDER';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';


