export const GET_ALL_TECHNOS = 'GET_ALL_TECHNOS';
export const SET_ALL_TECHNOS = 'SET_ALL_TECHNOS';
export const SET_TECHNO = 'SET_TECHNO';
export const SET_SELECTED_TECHNO = 'SET_SELECTED_TECHNO';
export const DELETE_TECHNO = 'DELETE_TECHNO';

