export const MODAL_VISIBILITY_SET = 'MODAL_VISIBILITY_SET';
export const MODAL_CONTENT_SET = 'MODAL_CONTENT_SET';
export const MODAL_NAME_SET = 'MODAL_NAME_SET';

export const SET_ALL_MODALS = 'SET_ALL_MODALS';
export const SET_CURRENT_MODAL = 'SET_CURRENT_MODAL';

